class InfeasibleError(ValueError):

    def __init__(self):
        pass
